name: 'songwoof'
version: 0.0.2
description: An absolute bare-bones web app.
#author: Andres Araujo <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  angular2: '>=2.0.0-beta.22 <3.0.0'
  http: '^0.11.3'
  js: '^0.6.0'
  firebase3: '^0.2.2'
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'

dev_dependencies:
  test: '^0.12.6'
  #angular2_testing: any

transformers:
- angular2:
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Firebase: 'package:firebase/firebase.dart'
- dart_to_js_script_rewriter